### ISSUE TITLE
Description for azuread_application_password has a character limit that is not present in portal

### ISSUE THREAD

**Issue by lewism77** [hashicorp/terraform-provider-azuread#396] opened 2021-02-11 01:18 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/azuread v1.3.0
+ provider registry.terraform.io/hashicorp/azurerm v2.46.1

### Affected Resource(s)

* `azuread_application_password`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azuread = "~>1.3.0"
  }
}

resource "azuread_application" "myapp" {
  display_name               = "TestApp"
  available_to_other_tenants = false
}

resource "azuread_application_password" "mypass" {
  application_object_id = azuread_application.myapp.id
  description           = "MyVeryVeryVeryVeryVeryVeryVeryLongDescription"
  value                 = "TESTS2"
  end_date_relative     = "17520h"
}
```

### Debug Output
https://gist.github.com/lewism77/c64b3974472f93b58576ccc21b2fa54f

### Expected Behavior

Since you can create a description of any length for a secret in Azure Portal it should not be an issue here.
OR
An error message actually indicating what field I need to adjust.

### Actual Behavior

An error message indicating "applicationKeyIdentifierValue" parameter is either missing or too long.

### Steps to Reproduce

Using the terraform script supplied above:
1. `terraform apply`

### Important Factoids
N/A

### References
N/A

* #0000

**Comment by lewism77** [comment] 2021-02-11 02:14
I see now in docs "description maps to the CustomKeyIdentifier property of the PasswordCredentials API resource."
Is there a reason for this? The description has no limit that I can see (in Portal) but it's subject to CustomKeyIdentifier restrictions. Maybe just some additional clarity on the docs would be good?

**Comment by manicminer** [comment] 2021-02-11 13:13
Hi @lewism77, thanks for reporting. We're aware of this issue, it has already been reported in #311. The root cause is that the API field for this property changed in Azure, but support was not added to the API we're currently using. We're working on an API migration at the moment which will enable us to resolve this.

Since this has been reported already, I'm going to close this as a duplicate of #311.

**Closed by manicminer** 2021-02-11 13:13 UTC
