### ISSUE TITLE
 azuread_user does not find Guest users by mail_nicknames t

### ISSUE THREAD

**Issue by dsfrederic** [hashicorp/terraform-provider-azuread#600] opened 2021-09-27 07:31 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

```
Terraform v1.0.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.78.0
+ provider registry.terraform.io/hashicorp/random v2.3.1
```

### Terraform Configuration Files

```hcl
data "azuread_users" "owners" {
  mailmail_nicknames = var.client.owners
}

data "azuread_users" "members" {
  user_principal_names = var.client.members
}
```

### Debug Output

```
Error: User not found with email alias: "XXXXX"
```

### Expected Behavior

Guest users should be found by defining the mail address. For ex. `user@othertenant.com`. 

### Current workaround 

Found in  `azuread_user does not find Guest users by user_principal_name` #275 

### Steps to Reproduce

1. `terraform apply`

**Comment by manicminer** [comment] 2021-09-27 11:25
Hi @dsfrederic, thanks for raising this. Guest users don't have a `mailNickname` field so at this time you would have to search by UPN, e.g. `jdoe_guest.com#EXT#@example.net`

This is an API design issue; as there is no `mailNickname` field, there's nothing for the provider to match against. In future we may be able to add the ability to look up using the `mail` field (see feature request #280).

**Comment by manicminer** [comment] 2021-09-29 21:32
As the root cause here is an API issue, and we're already tracking a feature request to look up users by their `mail` field, I'm going to close this for now. If I have misunderstood, please comment again with more details and we'll be happy to reopen and take another look. Thanks!

**Closed by manicminer** 2021-09-29 21:32 UTC
Labels: question, feature/users

**Comment by dsfrederic** [comment] 2021-09-30 12:39
Thanks for your response!
