### ISSUE TITLE
azuread_appliation: redirect URI "must have a trailing slash when there is no path segment" -- but azure allows

### ISSUE THREAD

**Issue by SeanKilleen** [hashicorp/terraform-provider-azuread#867] opened 2022-08-18 21:32 UTC
Summary: I am importing existing Azure resources into Terraform. I noticed an issue where the existing value in Azure, when added to Terraform, was declared invalid by the azuread provider. In short, if a URL is valid in azure as `http://localhost:4200`, Terraform rejects it, insisting it must be `http://localhost:4200/`. Trying to understand if this is a bug with the provider being overly strict vs what Azure allows, or if it's part of a more generic "valid URL" check. 

Submitting this as a bug because it seems that the provider would want to consider values that are valid to Azure to be valid for TF as well.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v1.2.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.27.0
+ provider registry.terraform.io/hashicorp/azurerm v3.16.0

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

```hcl
resource "azuread_application" "webapp_app_registration" {

  # ...

  single_page_application {
    redirect_uris = var.webapp_app_registration_redirect_urls
  }

  # ...

```

Where one of the variables is `http://localhost:4200`

### Expected Behavior

Allow the URL of `http://localhost:4200` to be used as a redirect URL

### Actual Behavior

`Error: URI must have a trailing slash when there is no path segment` 

Unless I change to `http://localhost:4200/` which is fine; it just isn't what our current configuration is, which is coming from Azure itself.

**Comment by manicminer** [comment] 2022-08-18 23:45
Hi @SeanKilleen, thanks for reporting this. You are correct that the API accepts redirect URIs having no path and no trailing slash. However, when reading back the application manifest, the API appends a trailing slash for path-less URIs even if it was created without a trailing slash. This causes a perpetual diff in Terraform and so to overcome this inconsistency we avoid assigning path-less redirect URIs without a trailing slash.

As this is by design, and cannot be changed without causing other side effects as mentioned above, we won't be changing this and accordingly I'm going to close this as unplanned. I hope this helps to clear up the discrepancy, but please feel free to comment further if it does not. Thanks!

**Closed by manicminer** 2022-08-18 23:45 UTC

**Comment by SeanKilleen** [comment] 2022-08-19 00:02
@manicminer thanks for the confirmation! Given that, makes total sense to close it. 👍
