### ISSUE TITLE
azuread: GroupsClient.BaseClient.Post(): unexpected status 400 with OData error: Request_BadRequest: Request contains a property with duplicate values.

### ISSUE THREAD

**Issue by kyrios** [hashicorp/terraform-provider-azuread#624] opened 2021-10-11 07:02 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform 1.0.2
Azuread 2.6.0

### Affected Resource(s)

* `azuread_group`

### Terraform Configuration Files

```hcl
terraform{
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>2.80.0"
    }
    azuread = {
      source = "hashicorp/azuread"
      version = "~> 2.6.0"
    }
  }
}

data "azuread_client_config" "current" {}

resource "azuread_group" "example" {
  display_name     = "example"
  owners           = [data.azuread_client_config.current.object_id]
  security_enabled = true
}
```

### Debug Output

https://gist.github.com/kyrios/142a0ba5350047f3ec9611ea8fe2a05d

### Expected Behavior

No error

### Actual Behavior

`GroupsClient.BaseClient.Post(): unexpected status 400 with OData error: Request_BadRequest: Request contains a property with duplicate
│ values.`

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Important Factoids

We have been upgrading to 2.6.0 because of https://github.com/hashicorp/terraform-provider-azuread/issues/588

### References
https://github.com/hashicorp/terraform-provider-azuread/issues/588

* #0000

**Comment by kyrios** [comment] 2021-10-11 11:58
Maybe as some additional information: It worked a week ago with version 2.4.0

**Comment by mlcooper** [comment] 2021-10-12 12:53
I hit this with #567.  My workaround is to assign someone **other than myself** as an `owner` of the Azure AD group. Terraform then successfully creates the AAD group and automatically makes my ID an owner as well as the other individual I specified. It got me past this "duplicate values" error.

**Comment by kyrios** [comment] 2021-10-13 13:00
That workaround seems to be working. Thanks a lot for sharing it @mlcooper!

Here is the code we are using:

```hcl
owners = ["foo-bar-foo-1"]
  lifecycle {
    ignore_changes = [
      # Ignore changes to tags, e.g. because a management agent
      # updates these based on some ruleset managed elsewhere.
      owners,
    ]
  }

```

**Comment by gscher** [comment] 2021-11-05 07:14
Is there any update on this issue?

**Comment by manicminer** [comment] 2021-11-05 12:54
This issue is due to, and blocked by, an API bug which is reported at https://github.com/microsoftgraph/msgraph-metadata/issues/92

**Comment by rufer7** [comment] 2021-12-03 10:30
I faced the same error and was able to "fix" it by assigning the authenticated user principal to the directory role `Groups Administrator` as stated in the documentation

**Comment by ju-la-berger** [comment] 2021-12-16 16:22
In the enterprise I am working at, it is impossible for ordinary mortals to acquire such elevated rights.
 
My workaround for daily use in Terraform is to create the group via Azure CLI and import it into the state for further management via Terraform, e.g. like this:
 
~~~
AD_APP_DISPLAY_NAME='foo.bar'
AD_APP_TF_STATE_ADDR='module.foo.azuread_group.bar'

az ad group create --display-name "${AD_APP_DISPLAY_NAME}" --mail-nickname "$(cat /proc/sys/kernel/random/uuid)"

terraform import "${AD_APP_TF_STATE_ADDR}" "$(az ad group show --group "${AD_APP_DISPLAY_NAME}" --query 'objectId' --output 'tsv')"
~~~

(It is only the *creation* of the group that fails. Further modifications are working.)

**Comment by robertbrandso** [comment] 2022-01-04 14:32
I experienced this issue when I was authenticating using a service principal.

After I gave the Group.ReadWrite.All API permission to the SPN it worked.

This is also stated in the [documentation](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/group):

> When authenticated with a service principal, this resource requires one of the following application roles: `Group.ReadWrite.All` or `Directory.ReadWrite.All`
> 
> If using the `assignable_to_role` property, this resource additionally requires one of the following application roles: `RoleManagement.ReadWrite.Directory` or `Directory.ReadWrite.All`
> 
> When authenticated with a user principal, this resource requires one of the following directory roles: `Groups Administrator`, `User Administrator` or `Global Administrator`

I must admit it isn't the ideal solution to give such broad permissions.

**Comment by carsv** [comment] 2022-04-22 15:09
Verified Authz issue in my organization.
"unexpected status 400" is misleading -> should be 401 Unauthorized.

**Comment by 64J0** [comment] 2022-04-29 14:59
I'm having a similar problem, but with the newer version mentioned in this issue: https://github.com/hashicorp/terraform-provider-azuread/issues/789.

> GroupsClient.BaseClient.Get(): unexpected status 403 with OData error: Authorization_RequestDenied: Insufficient privileges to complete the operation.

**Comment by jvelasquez** [comment] 2022-08-09 16:36
If anyone comes across this issue, this did it for me (little dirty but can live with that code until this is fixed) - 

```hcl
locals {
  azuread_admin_group_mail_nickname = uuidv5("dns", "carbon.dev.xyz")
  azuread_admin_group_owners        = concat([data.azuread_service_principal.terraform_client.id], data.azuread_user.admin_user.*.id)
  azuread_admin_group_id           = shell_script.azuread_admin_group.output.id
}

provider "shell" {}

resource "shell_script" "azuread_admin_group" {
  lifecycle_commands {
    create = "az ad group create --display-name ${var.azuread_admin_group_name} --mail-nickname ${local.azuread_admin_group_mail_nickname}"
    read   = "az ad group show --group ${var.azuread_admin_group_name}"
    update = "az ad group delete --group ${var.azuread_admin_group_name} && az ad group create --display-name ${var.azuread_admin_group_name} --mail-nickname ${local.azuread_admin_group_mail_nickname}"
    delete = "az ad group delete --group ${var.azuread_admin_group_name}"
  }
}
```

**Comment by ju-la-berger** [comment] 2023-02-27 13:38
Not really. To my understanding, the root cause https://github.com/microsoftgraph/msgraph-metadata/issues/92 is still open.

However, a colleague of mine and me did some more testing and we found out that you **can** actually create an AD group of type `"Unified"` (i.e. an O365 group).

If you we use a **service principal** to authenticate (our `terraform apply` execution), we can create groups. We will not get the `Group.ReadWrite.All` or `Directory.ReadWrite.All` in our enterprise IT environment but we found that the combination of `Directory.Read.All`, `Group.Create`, `Group.Read.All`, and `User.Read.All` (meaning all those four permissions) are sufficient.

The following code snippet illustrates our finding.

```
data "azuread_client_config" "current" {}

# fails when applied as user principal: "GroupsClient.BaseClient.Post(): unexpected status 400 with OData error: Request_BadRequest: Request contains a property with duplicate values."
# succeeds when applied as service principal with API permissions "Directory.Read.All", "Group.Create", "Group.Read.All", "User.Read.All"
resource "azuread_group" "test_foo" {
  display_name     = "test-foo"
  security_enabled = true
}

# succeeds when applied as user principal
# succeeds when applied as service principal with API permissions "Directory.Read.All", "Group.Create", "Group.Read.All", "User.Read.All"
resource "azuread_group" "test_bar" {
  display_name     = "test-bar"
  security_enabled = true

  mail_enabled  = true
  mail_nickname = "test-bar"
  types         = ["Unified"]
  visibility    = "Private"
}

# succeeds when applied as service principal with API permissions "Directory.Read.All", "Group.Create", "Group.Read.All", "User.Read.All"
resource "azuread_group" "test_foo_with_owners_and_members" {
  display_name     = "test-foo-with-owners-and-members"
  security_enabled = true

  members = local.owner_object_ids
  owners  = concat([data.azuread_client_config.current.object_id], local.owner_object_ids) # Do NOT forget to add the service principal's object ID here!
}
```

**Comment by manicminer** [comment] 2023-02-27 19:21
Hi all, since it seems there is no traction as yet with fixing this in the API, I am proposing a potential fix for this error by retrying the group creation when this error is detected _and_ the calling principal has been specified as an owner. The workaround relies on the other side of this API bug, that the calling principal is auto-added behind the scenes and the group is subsequently returned having the calling principal as an auto-appended owner.

If anyone is able to test out by compiling the provider locally from the `bugfix/group-400-owner` branch (see #1037), any such feedback will be greatly appreciated as it's not feasible to field-test this workaround in all circumstances. Thanks!

**Closed** 2023-03-01 21:41 UTC
Labels: feature/groups, upstream-microsoft, api/microsoft-graph, api-bug
