### ISSUE TITLE
Manage API permission consent via Terraform

### ISSUE THREAD

**Issue by icereed** [hashicorp/terraform-provider-azuread#518] opened 2021-08-13 12:22 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hello folks,

I would like to manage the API permission consent using this provider.
The goal would be to manage the settings highlighted in this screenshot:

![API permissions screenshot](https://user-images.githubusercontent.com/444269/129355968-8a9ff5cb-2dda-4604-8ca9-9b6abd50c2b4.png)

### New or Affected Resource(s)

* azuread_api_permission_consent (just an idea)

**Comment by manicminer** [comment] 2021-08-16 00:36
Hi @icereed, thanks for requesting this. I believe there is already an issue tracking this, see https://github.com/hashicorp/terraform-provider-azuread/issues/230. Accordingly I'm going to mark this as a duplicate, and recommend subscribing to that issue for updates - however if I have misunderstood the feature request please let me know and I'll be happy to reopen this. Thanks!

**Comment by manicminer** [comment] 2021-08-16 00:37
Duplicate of #230

**Closed by manicminer** 2021-08-16 00:37 UTC
Labels: enhancement, feature/application, api/microsoft-graph
