### ISSUE TITLE
Bug azuread_application does not support "google.com" as one of its identifier_uris

### ISSUE THREAD

**Issue by kneekeel** [hashicorp/terraform-provider-azuread#1215] opened 2023-10-18 18:39 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

❯ terraform -v
Terraform v1.6.0
on darwin_arm64

* provider registry.terraform.io/hashicorp/azuread v2.33.0

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

```hcl
data "azuread_application_template" "google_cloud" {
  display_name = "Google Cloud / G Suite Connector by Microsoft"
}

resource "azuread_application" "google_cloud_sso" {
  display_name = "Google Cloud / G Suite Connector by Microsoft"
  template_id  = data.azuread_application_template.google_cloud.template_id

  identifier_uris = ["google.com"]

  web {
    redirect_uris = ["https://www.google.com/"]
    implicit_grant {
      access_token_issuance_enabled = false
      id_token_issuance_enabled     = false
    }
  }
}
```

### Expected Behavior

Application should have been created with the schemaless URI "google.com".

[Google's documentation: 4.a)](https://cloud.google.com/architecture/identity/federating-gcp-with-azure-ad-configuring-provisioning-and-single-sign-on#configure_saml_settings) requires this for SAML configuration. It is also one of the supported identifiers by Microsoft, [see documentation: 6.a)](https://learn.microsoft.com/en-us/azure/active-directory/saas-apps/google-apps-tutorial#configure-microsoft-entra-sso).

However, this is not supported by the [terraform-provider-azuread](https://github.com/hashicorp/terraform-provider-azuread/blob/main/internal/tf/validation/uri.go#L16L18): `v2.33.0` or `v2.43.0`(latest).

### Actual Behavior

```hcl
Error: URI has no host
│ 
│   with ...azuread_application.google_cloud_sso,
│   on .../application.tf line 24, in resource "azuread_application" "google_cloud_sso":
│   24:   identifier_uris = ["google.com"]
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by manicminer** [comment] 2023-10-18 20:35
Hi @kneekeel, thanks for reporting this. Unfortunately the API does not support SAML configurations for applications and this is the only configuration where schemaless URIs like this are allowed. Unfortunately we can't support this due to both an absence of API support for SAML configuration, and server-side validation which mirrors the validation we perform within the provider.

As we already have a number of issues open relating to SAML support, I'm going to close this issue in favor of #173. Please subscribe to that issue if you'd like future updates on SAML support. Unfortunately as mentioned, there is simply no API support at this time and so we are unable to implement this. Thanks again for raising this, you may also wish to speak to your Azure account representative if this is an important feature for you.

**Comment by manicminer** [comment] 2023-10-18 20:35
Duplicate of #173

**Closed by manicminer** 2023-10-18 20:35 UTC
Labels: saml/sso
