### ISSUE TITLE
403 error while creating azuread_service_principal

### ISSUE THREAD

**Issue by callppatel** [hashicorp/terraform-provider-azuread#544] opened 2021-09-01 19:03 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuread_service_principal`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

#Create Service Principal
resource "azuread_service_principal" "sp" {
  application_id               = azuread_application.adapp.application_id
  app_role_assignment_required = false
}

```

### Panic Output
```
Terraform will perform the following actions:

  # azuread_service_principal.sp will be created
  + resource "azuread_service_principal" "sp" {
      + account_enabled              = true
      + app_role_assignment_required = false
      + app_role_ids                 = (known after apply)
      + app_roles                    = (known after apply)
      + application_id               = "2689f43b-fa9c-489c-af28-18391ebbbbbb"
      + application_tenant_id        = (known after apply)
      + display_name                 = (known after apply)
      + homepage_url                 = (known after apply)
      + id                           = (known after apply)
      + logout_url                   = (known after apply)
      + oauth2_permission_scope_ids  = (known after apply)
      + oauth2_permission_scopes     = (known after apply)
      + object_id                    = (known after apply)
      + owners                       = [
          + "8be411e4-c09b-429b-90fd-b5968f7bbbbb",
        ]
      + redirect_uris                = (known after apply)
      + saml_metadata_url            = (known after apply)
      + service_principal_names      = (known after apply)
      + sign_in_audience             = (known after apply)
      + type                         = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
azuread_service_principal.sp: Creating...
╷
│ Error: Could not create service principal
│
│   with azuread_service_principal.sp,
│   on main.tf line 11, in resource "azuread_service_principal" "sp":
│   11: resource "azuread_service_principal" "sp" {
│
│ ServicePrincipalsClient.BaseClient.Post(): unexpected status 403 with OData error: Authorization_RequestDenied: When using this permission, the backing application of the service principal being created must
│ in the local tenant
```

### Expected Behavior
Above code is working fine with Azured provider 1.6.0 and we have below access for both "MS Graph" and "Azure Active Directory Graph"

![image](https://user-images.githubusercontent.com/17652733/131729519-061d9cd3-0090-45ea-8d92-6cc51685fa58.png)

Also with same service principal, I am able to create Service Principal by using API as documented here
https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-serviceprincipals?view=graph-rest-1.0&tabs=http

Service Principal should be created with "Application.ReadWrite.OwnedBy" role.  It woks fine when we switch to "Application.ReadWrite.All" but our organization doesnt allow to keep "Application.ReadWrite.All", ideally "Application.ReadWrite.OwnedBy" should work. https://docs.microsoft.com/en-us/graph/permissions-reference

<html>
<body>

Application.ReadWrite.OwnedBy | Manage apps that this app creates or owns | Allows the calling app to create other applications and service principals, and fully manage those applications and service principals (read, update, update application secrets and delete), without a signed-in user. It cannot update any applications that it is not an owner of. Does not allow management of consent grants or application assignments to users or groups. | Yes
-- | -- | -- | --

</body>
</html>
###

 Actual Behavior

### Steps to Reproduce

1. `terraform apply`

Plan: 1 to add, 0 to change, 0 to destroy.
azuread_service_principal.sp: Creating...
╷
│ Error: Could not create service principal
│
│   with azuread_service_principal.sp,
│   on main.tf line 11, in resource "azuread_service_principal" "sp":
│   11: resource "azuread_service_principal" "sp" {
│
│ ServicePrincipalsClient.BaseClient.Post(): unexpected status 403 with OData error: Authorization_RequestDenied: When using this permission, the backing application of the service principal being created must
│ in the local tenant
╵
### References

* #0000

**Comment by manicminer** [comment] 2021-09-02 10:39
Hi @callppatel, thanks for the bug report. As this seems to be a duplicate of #535, I'm going to close this issue in favor of that one. Thanks!

**Comment by manicminer** [comment] 2021-09-02 10:39
Duplicate of #535

**Closed by manicminer** 2021-09-02 10:39 UTC
