### ISSUE TITLE
azuread_application_certificate: end_date_relative parameter should calculate the end date of a certificate/key based on the start_date but it is calculated based on the current timestamp when TF apply is executed

### ISSUE THREAD

**Issue by chennagouda14** [hashicorp/terraform-provider-azuread#850] opened 2022-07-22 08:46 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v1.0.0
provider registry.terraform.io/hashicorp/azuread v2.20.0

### Affected Resource(s)

* `azuread_application_certificate`

### Terraform Configuration Files

•	For example, If the certificate is issued on 8th July 2022 & if it is valid for 1 year which means that the expiry date(end date) would be 8th July 2023.
•	So in the below terraform configuration, start date of the certificate has been specified as 8th July 2022 & the end_date_relative parameter with value as “8760h00m”(i.e 1 year), which calculates end date & it will be 8th July 2023.

```
resource "azuread_application" "example" {
  display_name = "example"
}

resource "azuread_application_certificate" "example" {
  application_object_id = azuread_application.example.id
  encoding                    = "pem"
  start_date                   = "2022-07-08T00:00:00Z"
  end_date_relative       = "8760h00m"
  type                            = "AsymmetricX509Cert"
  value                           = file("cert.pem")
}

```

### Debug Output

```error: KeyCredentialsInvalidEndDate: Key credential end date is invalid.```

### Expected Behavior

•	When terraform apply is executed by specifying end_date_relative  parameter with value 8760 hour(i.e 1 year) then the end_date of the certificate should be calculated from the start_date onwards. This is the expected behaviour.
•	The expected end_date should be 8th July 2023.
•	However, in terraform, the end_date parameter is calculated based on the current timestamp (NOT the start_date)
•	As per Azure PowerShell, if start date is specified without any end date then the end-date would be calculated as 1 year after the start-date.

### Actual Behavior

•	When terraform apply is executed, then we get the following error as “Key credential end date is invalid.”
![image](https://user-images.githubusercontent.com/90911826/180400813-239b2d1c-7b02-4325-9b1b-d9a4c1c29dc4.png)
 
•	This is because Terraform calculates end_date based on the current timestamp(when TF apply is executed) and not the start_date parameter.
•	When end_date_relative parameter is specified with 8760 hour(1 year) then the end_date of the certificate should be calculated from the start_date onwards & the end date should be 8th July 2023, but it is calculated based on the current timestamp so the end date becomes “one year after TF execution(i.e 22 July 2023)” and this exceeds the certificate expiry date so terraform throws an error that end_date is invalid.

### Steps to Reproduce

1. `terraform apply`

### References

•	Terraform reference:
        https://registry.terraform.io/providers/hashicorp/azuread/2.20.0/docs/resources/application_certificate

**Comment by Threpio** [comment] 2022-07-22 13:28
An exact copy of https://github.com/hashicorp/terraform-provider-azuread/issues/843 APART from which resource it affects.

Weird it would be written out like that twice.

I will adapt the PR there to reflect the changes required here aswell.

**Comment by manicminer** [comment] 2022-07-31 20:07
Duplicate of #843

**Closed by manicminer** 2022-07-31 20:07 UTC
Labels: duplicate
