### ISSUE TITLE
Conditional Access : terraform show missing required blocks when not defined in the policy

### ISSUE THREAD

**Issue by josefismael** [hashicorp/terraform-provider-azuread#668] opened 2021-11-19 18:38 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v1.0.11, azuread v2.9.0

### Affected Resource(s)
`terraform show` is missing the following blocks in the `azuread_conditional_access_policy` if they're not defined in the Conditional Access Policy itself:

`Grant_controls`
`Locations`

These are not necessarily required for policies that apply session controls or policies that do not have a location condition.

However since they are considered a required block for the resource, terraform plan errors out when the .tf config file is missing these blocks.

### Terraform Configuration Files
Can't share configuration files, but the only resource in question is `azuread_conditional_access_policy`

### Expected Behavior

Would expect to see the full config of the `azuread_conditional_access_policy` resource

### Actual Behavior

`Error: Insufficient grant_controls blocks
│
│   on CA_Policies.Config.tf line 329, in resource "azuread_conditional_access_policy" "ID_4790a04e-74ad-4cd0-acdc-67e26350326c":
│  329: resource "azuread_conditional_access_policy" "ID_4790a04e-74ad-4cd0-acdc-67e26350326c" {
│
│ At least 1 "grant_controls" blocks are required.
`

### Steps to Reproduce

If a .tf file is complete with everything listed in output from `terraform show`

1. `terraform plan`

### References

* #0000

**Comment by josefismael** [comment] 2021-11-22 15:41
Correct - I am importing conditional access policy resources in an attempt to capture a snapshot of what already exists in a client's environment. The import works as expected, and creates a .tfstate config with all the required blocks (`Grant_controls` and `locations`). I was hoping to be able to write the output of `terraform show` to create a .tf file, but that command only returns those 2 blocks if they're explicitly configured in the policy. 

If there is a better way to convert a .tfstate file to a more 'portable' .tf file this would solve my problem, but I wasn't able to find a good method to accomplish that.

**Comment by manicminer** [comment] 2021-11-22 18:38
Thanks for confirming @josefismael, I'll see if something can be done to mitigate this.

**Comment by manicminer** [comment] 2021-11-22 22:04
@josefismael Unfortunately I haven't been able to reproduce this as yet. Would you be able to to share an example policy that triggers this for you, and the corresponding Terraform configuration that you would be trying to import to?

**Comment by stawik-mesa** [comment] 2022-01-11 07:29
Hi, we are facing the same issue, I tried to rollout this policy via Terraform: https://github.com/AlexFilipin/ConditionalAccess/blob/master/PolicyRepository/Data%20protection/500%20-%20RING%20-%20Data%20protection%20-%20All%20apps%20No%20persistent%20browser%20session%20When%20on%20untrusted%20device.json

Same issue:

```
At least 1 "grant_controls" blocks are required.
```

**Comment by josefismael** [comment] 2022-01-12 16:57
Coming back to this - the grant_controls block is required as per the documentation [here](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/conditional_access_policy).

My problem was that if the Grant_controls aren't explicitly defined in the policy itself, `terraform show` doesn't return the block at all.

I haven't tested this with the newer versions of terraform or AAD provider, but it sounds like the same deficiency is present. Basically boils down to whether or not `terraform show` should reveal all the required blocks/arguments of the resource (I think it should).

**Comment by manicminer** [comment] 2022-01-17 12:46
Having done some more testing with the API around `grantControls`, it appears the API does require this to be specified - so the schema for this resource is appropriate.

For the wider issue of Terraform not showing nil values from state when importing a resource, that behavior is not handled by the provider. When reading a policy (e.g. during import), the provider sets the `grant_controls` block and if this comes back as null on an existing policy, there isn't much we can do about that. Accordingly, since there's nothing to do here, I'm going to close this issue for now. Please feel free to comment further if I have misunderstood the ask here and I'll be glad to take another look. Thanks!

**Closed by manicminer** 2022-01-17 12:46 UTC
Labels: bug, feature/conditional-access
