### ISSUE TITLE
Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by Uvindu96** [hashicorp/terraform-provider-azuread#675] opened 2021-11-23 16:54 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version
- Terraform version v0.14.6
- AzureAD Provider version  2.10.0

### Affected Resource(s)

* `azuread_service_principal_password`
* `time_rotating`

### Description 
For the AD app secret rotation I have configured a `time_rotating` resource and `rotate_when_changed` attribute to the `azuread_service_principal_password` resource.

```
resource "time_rotating" "test" {
  rotation_days = 20
  lifecycle {
    create_before_destroy = true
  }
}
resource "random_password" "password" {
  length            = var.password_length
  special           = true
  lifecycle {
    create_before_destroy = true
  }
}

resource "azuread_service_principal_password" "service_principal_password" {
  service_principal_id = var.sp_internal_id
   rotate_when_changed = {
    rotation = time_rotating.test.id
  }
  lifecycle {
    create_before_destroy = true
  }
}
````
**According to this configuration I can change the rotation by days, but when I try to set the rotation based on minutes by using the attribute `rotation_minutes` it gives me the following error.**

```
Error: Provider produced inconsistent result after apply

When applying changes to
module.test-storage-account-dev-ops-ad-sp-password.time_rotating.test,
provider "registry.terraform.io/hashicorp/time" produced an unexpected new
value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```
Is there any solution for this error ? Or is there any workaround that I can follow ? much appreciate your help on this :)

**Comment by manicminer** [comment] 2021-11-24 13:11
Hi @Uvindu96, we're aware of some consistency related bugs with this resource. These are difficult to track down since reproduction depends on a number of factors, some outside our control.

Would you be able to post a [debug trace](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs#logging-and-tracing) which will show the HTTP requests involved leading up to this error?

**Comment by Uvindu96** [comment] 2021-11-25 04:33
Hi @manicminer Thanks for looking into this, I just tried to change the `rotation_hours` to `rotation_minutes` then again I got the same error, I exported all the related logs, please check the following log file,
**Log File :** 
[apply-log.txt](https://github.com/hashicorp/terraform-provider-azuread/files/7600204/apply-log.txt)

**Comment by manicminer** [comment] 2021-11-25 10:52
Hi @Uvindu96, thanks for the log output. Looking at it again more closely, I see that the error is actually originating from the `time_rotating` resource and not the `azuread_service_principal_password` resource.

Since this issue relates to a different provider, with different maintainers, I'm going to transfer this issue over to the [hashicorp/terraform-provider-time](https://github.com/hashicorp/terraform-provider-time) repository and hopefully it can be looked into there.

**Comment by Uvindu96** [comment] 2021-11-26 10:44
@manicminer Thanks for the follow up, I have created this issue in the https://github.com/hashicorp/terraform-provider-time repo to keep a track of this issue.

**Comment by manicminer** [comment] 2021-12-02 22:35
Thanks @Uvindu96, you beat me to it :)

I'll close this issue in favor of https://github.com/hashicorp/terraform-provider-time/issues/57

**Closed by manicminer** 2021-12-02 22:35 UTC
Labels: bug, feature/application
