### ISSUE TITLE
sign_in_audience in Azure AD Application doesn't support AzureADandPersonalMicrosoftAccount

### ISSUE THREAD

**Issue by Szer** [hashicorp/terraform-provider-azuread#475] opened 2021-07-02 13:19 UTC
[According to Azure AD Docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/supported-accounts-validation) there are ~3~4 possible audience for Azure App:
- AzureADMyOrg
- AzureADMultipleOrgs
- AzureADandPersonalMicrosoftAccount
- PersonalMicrosoftAccount

Latest (1.6.0) `azuread` provider supports only 2 out of 4:
https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application#sign_in_audience
with `AzureADMyOrg` by default.

When I'm trying to create App with unsupported audience I get expected error:
```Error: expected sign_in_audience to be one of [AzureADMyOrg AzureADMultipleOrgs], got AzureADandPersonalMicrosoftAccount```

Could you please add support for `AzureADandPersonalMicrosoftAccount`?

Updated: There are actually 4 possible audience. Added `PersonalMicrosoftAccount`

**Comment by manicminer** [comment] 2021-07-02 15:04
Hi @Szer, thanks for requesting this feature. We [recently merged](https://github.com/hashicorp/terraform-provider-azuread/pull/461) support for `AzureADandPersonalMicrosoftAccount` and `PersonalMicrosoftAccount` values for the `sign_in_audience` property and this will be included in the next release of the provider. For some additional context, the next release of the provider will be a major release (v2.0) which includes many new features that we were previously unable to add without introducing breaking changes. You can find out more about this in #323.

This particular feature was already requested in #408, as such I'm going to close this one as a duplicate. We appreciate your feature requests and encourage you to open further issues if there's a feature missing that isn't already covered in an existing issue. Thanks!

**Comment by manicminer** [comment] 2021-07-02 15:05
Duplicate of #408

**Closed by manicminer** 2021-07-02 15:04 UTC
