### ISSUE TITLE
directory_role_assignment - Missing option to set PIM directory role as eligible instead of active

### ISSUE THREAD

**Issue by MrNewgarden** [hashicorp/terraform-provider-azuread#1474] opened 2024-09-23 12:44 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
When assigning a MS Entra ID security group that has assignable_to_role = true there is no way to make the role to be eligible instead of permanent active. Which means we need to go into the groups and change all roles from active to eligible, and then comment out all the roles assigned, so we don't have drift in state.

### New or Affected Resource(s)
resource "azuread_directory_role_assignment" "example" {
  role_id                      = azuread_directory_role.example.template_id
  principal_object_id = data.azuread_user.example.object_id
  **eligible                      = true**
}

* azuread_directory_role_assignment

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

resource "azuread_directory_role_assignment" "example" {
  role_id                      = azuread_directory_role.example.template_id
  principal_object_id = data.azuread_user.example.object_id
  eligible                      = true
}
```

### References

* #0000

**Comment by manicminer** [comment] 2024-09-24 22:04
Hi @MrNewgarden, thanks for requesting this. I believe this is a duplicate of #1470 - noting that this requires a new resource as PIM directory role assignments are a different API than traditional role assignments (which are implemented as memberships). I'll close this one as a duplicate, please subscribe to #1470 for updates, thanks!

**Closed by manicminer** 2024-09-24 22:04 UTC
