### ISSUE TITLE
azuread_user: Terraform update to 0.15 forces password reset of users

### ISSUE THREAD

**Issue by xlz-jgoutin** [hashicorp/terraform-provider-azuread#427] opened 2021-04-23 09:33 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v0.15.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.4.0

### Affected Resource(s)

* `azuread_user`

### Terraform Configuration Files

```hcl
resource "random_password" "test" {
  length   = 16
  special  = false
}

resource "azuread_user" "test" {
  user_principal_name = "test@example.com"
  display_name        = "Test"
  password            = random_password.test.result
}
```

### Expected Behavior

No changes on users.

### Actual Behavior

Terraform plan to change users passwords:
```
  # azuread_user.azw_users["<removed_sensitive_value>"] will be updated in-place
  ~ resource "azuread_user" "azw_users" {
      + city                           = ""
      + country                        = ""
        id                             = "<removed_sensitive_value>"
      + immutable_id                   = ""
      + mobile                         = ""
      + onpremises_sam_account_name    = ""
      + onpremises_user_principal_name = ""
      # Warning: this attribute value will be marked as sensitive and will
      # not display in UI output after applying this change
      ~ password                       = (sensitive value)
      + physical_delivery_office_name  = ""
      + postal_code                    = ""
      + state                          = ""
      + street_address                 = ""
        # (13 unchanged attributes hidden)
    }
```

### Steps to Reproduce

Have an applied Terraform 0.14 configuration with managed users.
Upgrade to Terraform 0.15
Run `terraform apply`

### Important Factoids

If looking into the state, the `password` field correctly matches the requested value. So no change should be required.

No issue if using Terraform 0.14.10.

### References

* https://github.com/hashicorp/terraform-provider-azuread/issues/377#issuecomment-824836988

**Comment by manicminer** [comment] 2021-06-21 14:45
Hi @xlz-jgoutin, thanks for reporting this. Although this is an upstream behavior with Terraform itself, rather than the provider, in this case the value is not changed and the password isn't actually reset - it's safe to apply this plan.

Since there's no unexpected behavior here, I'm going to close this issue for now, but please feel to reply with additional details if you are observing the actual password being reset. Thanks!

**Closed by manicminer** 2021-06-21 14:45 UTC
Labels: bug, feature/users, upstream-terraform
