### ISSUE TITLE
azuread_invitation permission denied w/ service principal and client secret

### ISSUE THREAD

**Issue by whoracle** [hashicorp/terraform-provider-azuread#599] opened 2021-09-27 06:52 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

terraform -v
Terraform v0.14.5
+ provider registry.terraform.io/fortinetdev/fortios v1.11.0
+ provider registry.terraform.io/hashicorp/azuread v2.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.61.0
+ provider registry.terraform.io/hashicorp/vault v2.20.0

### Affected Resource(s)

* `azuread_invitation`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azuread = {
      source  = "hashicorp/azuread"
      version = "~> 2.4.0"
    }
  }
}

provider "azuread" {
  tenant_id = "3ddc5253-4a78-441a-a7c3-b51581c5d417"  # the "customer" tenant
  client_id = "REDACTED"
}

resource "azuread_invitation" "this" {
  user_email_address = "some.user@some.org"
  redirect_url       = "https://portal.azure.com"
}
```

### Expected Behavior

User invitation should be sent

### Actual Behavior

I'm getting the following error on `terraform apply`:

```bash
Error: Could not create invitation

  on ../../modules/invite_user/invitation.tf line 15, in resource "azuread_invitation" "this":
  15: resource "azuread_invitation" "this" {

InvitationsClient.BaseClient.Post(): unexpected status 401 with OData error:
Unauthorized: Insufficient privileges to perform requested operation by the
application '00000003-0000-0000-c000-000000000000'.
ControllerName=MSGraphInviteAPI, ActionName=CreateInvite, URL absolute
path=/api/3ddc5253-4a78-441a-a7c3-b51581c5d417/invites
```

### Steps to Reproduce

* Enterprise Application as Service Principal in two tenants (main and customer)
* Permissions in both Tenants (yes, I took the shotgun approach in the end):
    User.Invite.All
    User.Read
    User.ReadWrite.All
    Directory.ReadWrite.All
* Using that principal with client secret in multiple subscriptions in the home tenant as well as the one subscription in the second tenant with azurerm with no issues at all

1. `terraform apply`

### Important Factoids

Running in Azure Germany

### References

* None that I know of

**Comment by whoracle** [comment] 2021-09-27 06:53
I'm not sure if this is a bug, a "problem" with the documentation or a problem with my reading of the docs or something else Im doing wrong, but I can't figure this one out.

According to all docs I can find this should work. What am I missing here?

If I just missed some docs, kindly point me to the right direction. Thanks!

**Comment by manicminer** [comment] 2021-09-27 11:18
Hi @whoracle, thanks for reporting. We are now trying to document the required permissions by resource based on our testing in Azure Public. It's possible the permissions may be different, alas we don't have access to a tenant/subscription in Azure Germany.

Have you tried with a very broad API permission such as `Directory.ReadWrite.All` (this is somewhat of a superuser permission to my knowledge)? Also are you sure the necessary app role assignments (i.e. admin consent) have been granted for the SP? Thanks!

**Comment by whoracle** [comment] 2021-09-30 13:38
Hi @manicminer . From what I can see I've granted `Directory.ReadWrite.All` and have granted Consent. At least from what I can see via azure portal. I'll try to gather a few screenshots tomorrow from both ends if that helps?

**Comment by manicminer** [comment] 2021-09-30 15:44
@whoracle Screenshots would be handy, as well as a [log trace](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs#logging-and-tracing) if you can generate one. With that we should be able to confirm whether tne issue lies with the provider or the API. Though I suspect this is likely an API issue since I don't believe the provider is doing anything unexpected.

**Comment by whoracle** [comment] 2021-10-04 06:24
Hi @manicminer - attached is the debug.log of the following call:
`TF_LOG=DEBUG terragrunt apply -auto-approve --target=module.invite_mgerber.azuread_invitation.this > debug.log` - Resource targeting so the log is at least somewhat concise. Running the same without targeting yields the same results.

[debug.log](https://github.com/hashicorp/terraform-provider-azuread/files/7275841/debug.log)

Also attached are two screenshots - Permissions of the Service Principal App in both tenants.
Home tenant:
![home_tenant](https://user-images.githubusercontent.com/5177571/135803201-5ccb00ad-4530-4ffd-86b6-9c44f81fe35a.png)
Managed tenant:
![managed_tenant](https://user-images.githubusercontent.com/5177571/135803213-717d417a-5642-4f93-a636-e2a37bacdb89.png)

Hope this helps.

**Comment by manicminer** [comment] 2021-10-04 18:34
Hi @whoracle, thanks for providing the screenshots and logs.

I think the problem is likely the type of API permissions that have been assigned. You will need to grant roles (application-level permissions) rather than the scopes (delegated permissions) you have assigned.

**Comment by whoracle** [comment] 2021-10-05 06:38
Hi @manicminer : I'm not sure I'm following you - App Roles are only available in the original tenant of the service principal - all other tenants access the principal via Enterprise Application. However, from both your answer and some information I gathered around the net I think my whole basic setup seems wrong somehow, and it's not the provider that's at fault, neither its documentation.

I'll take this up with microsoft. If it's OK I'll leave this issue open until I've resolved it, and will then provide a kind of "guide" on how to accomplish this for other users who might stumble over the same issue.

**Comment by manicminer** [comment] 2021-10-05 08:48
@whoracle We don't support multi-tenant applications for authenticating the provider at this time, you will likely need to create an app registration in each tenant being managed.

In order to enable us to focus on provider issues, I'm going to close this one for now. Although closed, the issue will not go anywhere and you'll be able comment further for 30 days. As this develops, if you believe the provider is at fault, please feel free to comment and I'll be happy to reopen. Thanks!

**Closed** 2021-10-05 08:48 UTC
Labels: question, feature/invitations
