### ISSUE TITLE
azuread_application fails to apply with 404 error on 2.34.0

### ISSUE THREAD

**Issue by FooBartn** [hashicorp/terraform-provider-azuread#1022] opened 2023-02-17 17:16 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

terraform version: 1.3.7
azuread version: 2.34.0

This does not occur after rolling back to 2.33.0

### Affected Resource(s)

* `azuread_application`

### Terraform Configuration Files

```hcl
resource "azuread_application" "this" {
  display_name = var.display_name
  identifier_uris = var.identifier_uris

  owners = concat(
    data.azuread_users.owners.object_ids,
    [data.azuread_client_config.current.object_id]
  )

  dynamic "app_role" {
    for_each = local.standard_app_roles
    content {
      allowed_member_types = [
        "User",
      ]
      description  = app_role.value
      display_name = app_role.value
      enabled      = true
      id           = random_uuid.app_role[app_role.value].result
    }
  }

  web {
    homepage_url  = "removed"
    redirect_uris = var.redirect_uris

    implicit_grant {
      access_token_issuance_enabled = false
      id_token_issuance_enabled     = var.allow_implicit_id_token
    }
  }

  group_membership_claims = var.group_membership_claims

}
```

### Expected Behavior

A successful plan (GET requests) that retrieve information about the application
should not result in a 404 on apply.

### Actual Behavior

```
Error: Could not update application with object ID: "<removed>" with module.terraform_cloud_sso.azuread_application.thison modules/azuread-application/application.tf line 20, in resource "azuread_application" "this":

resource "azuread_application" "this" {

ApplicationsClient.BaseClient.Patch(): unexpected status 404 with OData error: Request_ResourceNotFound: Resource '' does not exist or one of its queried reference-property objects are not present.

Error: Could not update application with object ID: "<removed>" with module.hashicorp_cloud_platform_sso.azuread_application.thison modules/azuread-application/application.tf line 20, in resource "azuread_application" "this":

resource "azuread_application" "this" {

ApplicationsClient.BaseClient.Patch(): unexpected status 404 with OData error: Request_ResourceNotFound: Resource '' does not exist or one of its queried reference-property objects are not present.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Rolling back to 2.33.0 resolves this issue.

### References

* #0000

**Comment by manicminer** [comment] 2023-02-17 19:55
Thanks for reporting this issue. This is a known regression with a fix incoming. However, since this was already reported in #1017, I'm going to close this issue in favor of that one. Please subscribe to #1017 for updates. Thanks!

**Closed by manicminer** 2023-02-17 19:55 UTC
