### ISSUE TITLE
AzureAD group owners bugs

### ISSUE THREAD

**Issue by patrickmarabeas** [hashicorp/terraform-provider-azuread#464] opened 2021-06-17 12:11 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuread_group`

### Terraform Configuration Files

```hcl
resource "azuread_group" "example" {
  display_name = "example"
  users = [
    # Service Principal
    # User A
  ]
}
```

### Debug Output

```
Error: deleting group member "XXX" from Group with ID "YYY": 
. . .
The group must have at least one owner, hence this owner cannot be removed.
. . .
```

### Expected Behavior

1. Service Principals should be legitimate owners of a group
2. Owners should be added and removed freely (conforming to the limitation that once an owner is specified, an owner must always be specified)

### Actual Behavior

1. Service Principals set as group owners do not count as the one owner. Adding an additional user as an owner and removing them results in the above error.
2. Removal occurs before addition of new owners. In cases where a group has a single owner and they are being replaced, the above error occurs as the current sole owner is removed before the new owner is added.

### Steps to Reproduce

1. Create a group with a Service Principal set as an owner
2. Add an additional user as an owner
3. Remove the additional user from owners
4. ERROR
5. Add the user back as an owner
6. Replace the user with another owner
7. ERROR

### References

* https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-accessmanagement-managing-group-owners

**Comment by manicminer** [comment] 2021-06-17 13:12
Hi @patrickmarabeas, thanks for reporting this! I'll take a look and try to reproduce - in theory this shouldn't be happening as we deliberately add new owners before removing the old ones. We don't consider service principal owners any differently than other types of principals, but a group should definitely not be orphaned with no owners.

Can you confirm if you are using the MS Graph beta or not? Does the same thing happen with the other API?

Thanks!

**Comment by patrickmarabeas** [comment] 2021-06-25 03:46
Not using MS Graph as far as I know - we've been using v1.0.0 of the provider, and I've only just tested it with v1.6.0.

Here's config and logs for service principal not being considered an owner:

```
terraform {
  required_version = "= 0.14.5"
  required_providers {
    azuread = {
      source = "hashicorp/azuread"
      version = "1.6.0"
    }
  }
}

provider "azuread" {
  client_id       = "***"
  tenant_id       = "***"
  client_secret = "***"
}

data "azuread_client_config" "current" {}

data "azuread_user" "user" {
  user_principal_name = "patrick.marabeas@***.com"
}

resource "azuread_group" "test_group" {
  name = "test_group"
  owners = [
    data.azuread_client_config.current.object_id,
    data.azuread_user.user.object_id,
  ]
}
```

Log:

```
Terraform will perform the following actions:

  # azuread_group.group will be created
  + resource "azuread_group" "group" {
      + display_name            = (known after apply)
      + id                      = (known after apply)
      + mail_enabled            = (known after apply)
      + members                 = (known after apply)
      + name                    = "test_group"
      + object_id               = (known after apply)
      + owners                  = [
          + "***",
          + "***",
        ]
      + prevent_duplicate_names = false
      + security_enabled        = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

. . . 

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

Update group owners to remove myself:

```
resource "azuread_group" "test_group" {
  name = "test_group"
  owners = [
    data.azuread_client_config.current.object_id,
  ]
}
```

Log:

```
Terraform will perform the following actions:

  # azuread_group.group will be updated in-place
  ~ resource "azuread_group" "group" {
        id                      = "***"
        name                    = "test_group"
      ~ owners                  = [
          - "***",
            # (1 unchanged element hidden)
        ]
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Error: Removing group owner "***" from group with object ID: "***"

  on test.tf line 42, in resource "azuread_group" "group":
  42: resource "azuread_group" "group" {

graphrbac.GroupsClient#RemoveOwner: Failure responding to request:
StatusCode=400 -- Original Error: autorest/azure: Service returned an error.
Status=400 Code="Unknown" Message="Unknown service error"
Details=[{"odata.error":{"code":"Request_BadRequest","date":"2021-06-25T03:35:26","message":{"lang":"en","value":"The
group must have at least one owner, hence this owner cannot be
removed."},"requestId":"***"}}]
```

Similarly if an additional owner is added, while removing a user (service principal still as owner):

```
data "azuread_user" "user2" {
  user_principal_name = "***@***.com"
}

resource "azuread_group" "group" {
  name = "test_group"
  owners = [
    data.azuread_client_config.current.object_id,
    data.azuread_user.user2.object_id,
  ]
}
```

Log:

```
Terraform will perform the following actions:

  # azuread_group.group will be updated in-place
  ~ resource "azuread_group" "group" {
        id                      = "***"
        name                    = "test_group"
      ~ owners                  = [
          - "***",
          + "***",
            # (1 unchanged element hidden)
        ]
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Error: Removing group owner "***" from group with object ID: "***"

  on test.tf line 46, in resource "azuread_group" "group":
  46: resource "azuread_group" "group" {

graphrbac.GroupsClient#RemoveOwner: Failure responding to request:
StatusCode=400 -- Original Error: autorest/azure: Service returned an error.
Status=400 Code="Unknown" Message="Unknown service error"
Details=[{"odata.error":{"code":"Request_BadRequest","date":"2021-06-25T03:43:20","message":{"lang":"en","value":"The
group must have at least one owner, hence this owner cannot be
removed."},"requestId":"***"}}]
```

**Comment by patrickmarabeas** [comment] 2021-06-26 07:10
Reviewed the permissions on the service principal, but I'm pretty sure `Groups Administrator` is the only one doing anything and the rest are just legacy while trying to get it to work!

```
Azure Active Directory Graph
    Directory.Read.All

Microsoft Graph
    Directory.Read.All
    Group.Create
    Group.Read.All
    FGroup.ReadWrite.All
    User.Read.All

Directory Roles
    Groups Administrator
```

**Comment by hbuckle** [comment] 2021-06-30 18:23
I've seen the same thing using msgraph - 3 owners on the group, 1 service principal and 2 users. Run terraform to remove the 2 users but leave the service principal and got this error

```
GroupsClient.BaseClient.Delete(): unexpected status 400 with OData error:
Request_BadRequest: The group must have at least one owner, hence this owner
cannot be removed.
```

**Comment by hbuckle** [comment] 2021-07-02 08:59
I'm wondering if something has change in Azure AD, because the portal is giving the same error.
I have definitely created groups in the past that are just owned by a service principal

**Comment by manicminer** [comment] 2021-07-02 15:34
Sorry for the delay in responding on this one. I've done some testing with the scenario you've both described (i.e. multiple owners including an SP, then remove all owners but the SP) and I'm getting the same error from both AAD Graph API and MS Graph API. I don't know if this is a new behavior or not, since this _exact_ scenarios isn't captured by our acceptance tests. The closest scenarios we do have test coverage for is removing a single user owner and replacing them with a single SP owner, which bizarrely works just fine.

This is definitely an API / service issue, the provider is doing the right thing regardless of the API selected. We could potentially screen for this at plan time and warn the operator before the apply starts, but first I'd like to find out if this is an expected behavior from the API or a bug. It certainly seems like a bug given that it allows you to delete all owners when they are users (taking the group to having no owners) and adding a single service principal owner.

Marking as upstream blocked whilst I follow up with our contacts to find out more.

**Comment by manicminer** [comment] 2021-07-02 15:57
Reported in #473: seems like this breaks group creation when no owners are specified, due to the way the provider appends the calling SP as owner at creation time.

**Comment by manicminer** [comment] 2021-07-28 21:56
This issue has some overlap with #478, accordingly I'm going to close it in favor of tracking these intertwined group-related bugs in a single place. Please subscribe to #478 for updates. Thanks!

**Closed by manicminer** 2021-07-28 21:56 UTC
Labels: bug, feature/groups, upstream-microsoft
