### ISSUE TITLE
Unable to create azuread_application with v2.34.0

### ISSUE THREAD

**Issue by juicybaba** [hashicorp/terraform-provider-azuread#1017] opened 2023-02-17 02:31 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version
terraform `v1.3.7`
azuread `v2.34.0`

### Affected Resource(s)

* `azuread_application `

### Terraform Configuration Files

```hcl
data "azuread_client_config" "default" {}

resource "azuread_application" "default" {
  display_name    = format("app-%s-%s", var.project.name, var.project.environment.name)
  identifier_uris = []
  owners = concat(
    [data.azuread_client_config.default.object_id]
  )
}
```

### Debug Output
│ ApplicationsClient.BaseClient.Post(): unexpected status 404 with OData
│ error: Request_ResourceNotFound: Resource '' does not exist or one of its
│ queried reference-property objects are not present.

### Expected Behavior
unable to create brand new `azuread_application` with above code, the code works with `v2.33.0` but not `v2.34.0`, and it doesn't seem to impact the existing `azuread_application`

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by juicybaba** [comment] 2023-02-17 02:33
API permission of the account terraform is using to create new `azuread_application`
![image](https://user-images.githubusercontent.com/79539850/219534827-31ec87a2-ccd7-4c7a-a487-d186cf871143.png)

**Comment by lupa95** [comment] 2023-02-17 11:03
+1 to this. We see the same error. Everything worked on v2.33.0

**Comment by kbild** [comment] 2023-02-17 11:18
+1, same here, working with v2.33.0, not with v2.34.0

**Comment by Kapsztajn** [comment] 2023-02-17 11:27
+1 same issue

**Comment by rikribbers** [comment] 2023-02-17 12:30
+1 Updating an existing application also is broken

**Comment by shubhamsetia681** [comment] 2023-02-17 13:39
+1, facing the same issue since this update with azuread provider version.

**Comment by plejon** [comment] 2023-02-17 13:49
+1

**Comment by artisticcheese** [comment] 2023-02-17 18:35
How do you revert back to previous version of provider in TF?

**Comment by eohlde** [comment] 2023-02-17 18:58
> How do you revert back to previous version of provider in TF?
Add an _azuread_ block to the _required_providers_ block.
This is my current work-around:

```terraform
terraform {
  backend "azurerm" {}
  required_providers {

    azuread = {
      source = "hashicorp/azuread"
      version = "2.33.0"
    }
  }
```

**Comment by manicminer** [comment] 2023-02-17 19:07
Thanks for reporting this issue. Looking at this closely, this does appear to be a regression in the latest release. We will ship a patch release today containing a fix for this, in the meantime you can pin to v2.33.0 to avoid this issue. Apologies for the inconvenience caused.

**Closed** 2023-02-17 21:01 UTC
Labels: regression, feature/application
