### ISSUE TITLE
AzureAD v3 - data "azuread_group" Error: Could not retrieve group members for group with object ID

### ISSUE THREAD

**Issue by ti-ro** [hashicorp/terraform-provider-azuread#1498] opened 2024-09-27 05:38 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

Terraform v1.9.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v3.0.0
+ provider registry.terraform.io/hashicorp/azurerm v4.3.0
+ provider registry.terraform.io/hashicorp/random v3.6.3
+ provider registry.terraform.io/hashicorp/time v0.12.1

### Affected Resource(s)

* data `azuread_group`

### Terraform Configuration Files

```hcl
data "azuread_group" "aad_group" {
  display_name = var.aad_group_displayname
}
```

### Panic Output

`╷
│ Error: Could not retrieve group members for group with object ID: "/groups/xxx-xxx-xxx-xxx"
│
│   with module.EXAMPLE.data.azuread_group.aad_group,
│   on ..\..\..\..\modules\azure\EXAMPLE\iam.tf line 5, in data "azuread_group" "aad_group":
│    5: data "azuread_group" "aad_group" {
│
│ unexpected status 400 (400 Bad Request) with error: Request_BadRequest: Unexpected segment DynamicPathSegment. Expected property/$value.`

### Expected Behavior

Retrieve the Group information from the data source

### Actual Behavior

throws an Error 

### Steps to Reproduce

Create a Data Resource for azuread_group, input the display name of an existing Entra Group.

1. `terraform apply`

### Important Factoids

None. Worked prior 3.0.0

### References

* #0000

**Comment by nixlim** [comment] 2024-09-27 10:56
Yep, it broken! Getting the same thing

**Comment by GraemeMeyerGT** [comment] 2024-09-27 10:57
I'm going to jump on with what I assume is a related issue - I get a parsing error for data.azuread_service_principal


```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: expected "object_id" to be a valid UUID, got /servicePrincipals/120326c9-ca1a-4198-b326-4417d7b1fc25
│
│   with azurerm_key_vault_access_policy.terraform,
│   on az-key-vault-access-policy.tf line 12, in resource "azurerm_key_vault_access_policy" "terraform":
│   12:   object_id = data.azuread_service_principal.terraform.id
│
```

I've rolled back to 2.53.1 and the error goes away.

**Comment by sunevnuahs** [comment] 2024-09-27 11:05
Same here, pinning to 2.53.1 for now!

**Comment by michelefa1988** [comment] 2024-09-27 11:36
Same issue, needs to be hotifxed!!

**Comment by manicminer** [comment] 2024-09-27 11:44
@ti-ro Thanks for the report, we'll get this hotfixed.

**Comment by manicminer** [comment] 2024-09-27 11:44
@GraemeMeyerGT That is related, but not a bug. Please use the `object_id` attribute instead, e.g.

```terraform
resource "azurerm_key_vault_access_policy" "example-principal" {
  key_vault_id = azurerm_key_vault.example.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = data.azuread_service_principal.example.object_id

  key_permissions = [
    "Get", "List", "Encrypt", "Decrypt"
  ]
}
```

**Comment by digital-raver1** [comment] 2024-09-27 11:51
![image](https://github.com/user-attachments/assets/62e2cc22-0458-4134-811b-f9239aa39731)

**Comment by manicminer** [comment] 2024-09-27 12:01
Thanks @digital-raver1, that's the same error and will be fixed shortly

**Comment by manicminer** [comment] 2024-09-27 12:45
@simmonsl Thanks for the report, please be mindful of posting +1 comments as they pollute the issue thread. Per my above comments, this is being worked on and a fix will be out shortly.

**Closed** 2024-09-27 13:15 UTC
Labels: regression, feature/groups

**Comment by phatcher** [comment] 2024-09-27 21:05
> @GraemeMeyerGT That is related, but not a bug. Please use the `object_id` attribute instead, e.g.
> 
> ```hcl
> resource "azurerm_key_vault_access_policy" "example-principal" {
>   key_vault_id = azurerm_key_vault.example.id
>   tenant_id    = data.azurerm_client_config.current.tenant_id
>   object_id    = data.azuread_service_principal.example.object_id  # <-- `object_id`, not `id`
> 
>   key_permissions = [
>     "Get", "List", "Encrypt", "Decrypt"
>   ]
> }
> ```

You may not classify it as a bug, but it is a breaking change

**Comment by manicminer** [comment] 2024-10-01 00:01
@phatcher The docs for `azurerm_key_vault_access_policy` clearly show `object_id` as the appropriate attribute to reference; this has been the case for some time. I agree it is a breaking change, which is why this was done in a major release (which we strongly recommend you do not perform without fully testing your configs), and could have been better documented - I'll look to add this in the upgrade guide.

**Comment by sudheeshkj** [comment] 2024-10-14 06:28
Issue has been resolved
