### ISSUE TITLE
Currently Azure AD Provider does not allow configuring role management policies to configure PIM Settings

### ISSUE THREAD

**Issue by SuryenduB** [hashicorp/terraform-provider-azuread#863] opened 2022-08-16 13:19 UTC
Present version of the provider does not allow Role Settings to enforce PIM Configurations at the time of setting up users as Eligible members for a role. Please ensure that following API requests can be made from Terraform.

1. https://docs.microsoft.com/en-us/rest/api/authorization/role-management-policies/update?tabs=HTTP

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azuread_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by manicminer** [comment] 2022-08-18 23:31
Hi @SuryenduB, thanks for requesting this. We're tracking support for PIM related resources in a [single issue](#68) at this time, in order to consolidate upvotes and simplify tracking.

Accordingly, I'm going to close this as a duplicate of #68 for now. This is our most requested service and I can assure you it is on our roadmap. Thanks!

**Closed by manicminer** 2022-08-18 23:31 UTC
