### ISSUE TITLE
azuread_app_role_assignment should gracefully handle external delete

### ISSUE THREAD

**Issue by rgl** [hashicorp/terraform-provider-azuread#1036] opened 2023-02-26 10:28 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

2.35.0

### Affected Resource(s)

* `azuread_app_role_assignment`

### Debug Output

```
azuread_app_role_assignment.alice: Destroying... [id=d854582f-499b-4f61-b7fa-9ba8a4f1c912/appRoleAssignment/o0DNjznTSk-9zGhVC8iNMgfY2rlGFDBJhRaQi3rdWig]
azuread_app_role_assignment.alice: Still destroying... [id=d854582f-499b-4f61-b7fa-9ba8a4f1c912/ap...znTSk-9zGhVC8iNMgfY2rlGFDBJhRaQi3rdWig, 10s elapsed]
azuread_app_role_assignment.alice: Still destroying... [id=d854582f-499b-4f61-b7fa-9ba8a4f1c912/ap...znTSk-9zGhVC8iNMgfY2rlGFDBJhRaQi3rdWig, 20s elapsed]
azuread_app_role_assignment.alice: Still destroying... [id=d854582f-499b-4f61-b7fa-9ba8a4f1c912/ap...znTSk-9zGhVC8iNMgfY2rlGFDBJhRaQi3rdWig, 30s elapsed]
azuread_app_role_assignment.alice: Still destroying... [id=d854582f-499b-4f61-b7fa-9ba8a4f1c912/ap...znTSk-9zGhVC8iNMgfY2rlGFDBJhRaQi3rdWig, 40s elapsed]
azuread_app_role_assignment.alice: Still destroying... [id=d854582f-499b-4f61-b7fa-9ba8a4f1c912/ap...znTSk-9zGhVC8iNMgfY2rlGFDBJhRaQi3rdWig, 50s elapsed]
azuread_app_role_assignment.alice: Still destroying... [id=d854582f-499b-4f61-b7fa-9ba8a4f1c912/ap...znTSk-9zGhVC8iNMgfY2rlGFDBJhRaQi3rdWig, 1m0s elapsed]
azuread_app_role_assignment.alice: Still destroying... [id=d854582f-499b-4f61-b7fa-9ba8a4f1c912/ap...znTSk-9zGhVC8iNMgfY2rlGFDBJhRaQi3rdWig, 1m10s elapsed]
azuread_app_role_assignment.alice: Still destroying... [id=d854582f-499b-4f61-b7fa-9ba8a4f1c912/ap...znTSk-9zGhVC8iNMgfY2rlGFDBJhRaQi3rdWig, 1m20s elapsed]
azuread_app_role_assignment.alice: Still destroying... [id=d854582f-499b-4f61-b7fa-9ba8a4f1c912/ap...znTSk-9zGhVC8iNMgfY2rlGFDBJhRaQi3rdWig, 1m30s elapsed]
azuread_app_role_assignment.alice: Still destroying... [id=d854582f-499b-4f61-b7fa-9ba8a4f1c912/ap...znTSk-9zGhVC8iNMgfY2rlGFDBJhRaQi3rdWig, 1m40s elapsed]
azuread_app_role_assignment.alice: Still destroying... [id=d854582f-499b-4f61-b7fa-9ba8a4f1c912/ap...znTSk-9zGhVC8iNMgfY2rlGFDBJhRaQi3rdWig, 1m50s elapsed]
azuread_app_role_assignment.alice: Still destroying... [id=d854582f-499b-4f61-b7fa-9ba8a4f1c912/ap...znTSk-9zGhVC8iNMgfY2rlGFDBJhRaQi3rdWig, 2m0s elapsed]
azuread_app_role_assignment.alice: Still destroying... [id=d854582f-499b-4f61-b7fa-9ba8a4f1c912/ap...znTSk-9zGhVC8iNMgfY2rlGFDBJhRaQi3rdWig, 2m10s elapsed]
azuread_app_role_assignment.alice: Still destroying... [id=d854582f-499b-4f61-b7fa-9ba8a4f1c912/ap...znTSk-9zGhVC8iNMgfY2rlGFDBJhRaQi3rdWig, 2m20s elapsed]
azuread_app_role_assignment.alice: Still destroying... [id=d854582f-499b-4f61-b7fa-9ba8a4f1c912/ap...znTSk-9zGhVC8iNMgfY2rlGFDBJhRaQi3rdWig, 2m30s elapsed]
╷
│ Error: Deleting app role assignment for resource "d854582f-499b-4f61-b7fa-9ba8a4f1c912" with ID "o0DNjznTSk-9zGhVC8iNMgfY2rlGFDBJhRaQi3rdWig", got status 404
│
│ AppRoleAssignedToClient.BaseClient.Delete(): unexpected status 404 with OData error: Request_ResourceNotFound: Resource 'o0DNjznTSk-9zGhVC8iNMgfY2rlGFDBJhRaQi3rdWig' does not exist or one of its queried
│ reference-property objects are not present.
╵
```

### Expected Behavior

Expected it do gracefully handle the external delete and removed the resource from terraform.

### Actual Behavior

It retried the delete until it timeout without success.

### Steps to Reproduce

1. `terraform apply`
2. Go to the Azure Portal. Open the Enterprise Application. Manually delete an App Role assignment.
3. `terraform destroy`

**Comment by manicminer** [comment] 2023-04-27 17:48
@rgl Thanks for opening this issue. We do already implicitly handle resources that are deleted out of band, in both the scenario that you also deleted it from your configuration, or that you want to recreate it. This happens as part of the planning process, which is when resources are read and compared to their state representation and your configuration.

I was able to reproduce the error you're getting and I believe it's due to replication delays (i.e. eventual consistency) within Azure AD. If the app role assignment is deleted and then a `terraform plan` is very quickly generated, then the API will still return the (now deleted) app role assignment for a short period. Accordingly, Terraform believes it still exists and plans to delete it. After an indeterminable period of typically a few minutes, the API eventually stops returning the deleted object and Terraform will see this at plan time.

Ultimately this is down to eventual consistency within Azure AD and in a scenario like this, it's impossible for Terraform to reconcile during this period of backend replication. The best workaround is to delete the resource using Terraform (in band), or when deleting out-of-band, to wait for several minutes or however long it takes for the API to catch up.

Since this is more of a service issue than a bug within the provider, and since there's no feasible workaround or fix that we can effect, I'm going to close this issue as unplanned. If this continues to affect you, I would perhaps suggest opening an Azure support ticket, or contacting your Azure account manager to raise your concerns. Thanks!

**Closed by manicminer** 2023-04-27 17:48 UTC
Labels: question, feature/app-role-assignments
