### ISSUE TITLE
Error when creating Azure Active Directory group if use_microsoft_graph=true.

### ISSUE THREAD

**Issue by huwjeffries** [hashicorp/terraform-provider-azuread#473] opened 2021-06-30 14:03 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version
Terraform v1.0.1
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.6.0
+ provider registry.terraform.io/hashicorp/azurerm v2.65.0

### Affected Resource(s)
* `azuread_group`

### Terraform Configuration Files

My terraform (main.tf) looks like this:

```hcl
provider "azurerm" {
  features {}
  skip_provider_registration = true
}

provider "azuread" {
  use_microsoft_graph = true
}

resource "azuread_group" "groups" {
  display_name = "mygroup938"  
}
```

### Debug Output

https://gist.github.com/huwjeffries/34e924cf26a19a19453d848194f46fe2

### Panic Output

None

### Expected Behavior

It should create the Azure Active Directory group mygroup938.

### Actual Behavior

It creates mygroup938, but then it gives the error:
```
azuread_group.groups: Creating...
 Error: Could not remove temporary owner of group with ID: "901ea81c-aabd-43e6-876b-08246fd33e9a"
   with azuread_group.groups,
   on main.tf line 10, in resource "azuread_group" "groups":
   10: resource "azuread_group" "groups" {

 GroupsClient.BaseClient.Delete(): unexpected status 400 with OData error: Request_BadRequest: The group must have at
 least one owner, hence this owner cannot be removed.
```
It appears that it creates the group with me as the owner (which makes sense), but it then tries to delete me as the owner. This is not allowed in Azure as all groups must have at least one owner.

Setting use_microsoft_graph=false fixes the problem, but we'd like to use Microsoft graph going forward.

### Steps to Reproduce

1. On your local machine, create the very simple main.tf file as listed above.
2. Ensure you are logged into azure (`az login`)
2. `terraform init`
3. `terraform plan`
3. `terraform apply`

**Comment by manicminer** [comment] 2021-07-02 16:03
Hi @huwjeffries, thanks for reporting this. I am able to reproduce this issue with MS Graph; this appears to be a new behavior which we're trying to raise upstream as an API or service issue. The same thing actually happens with AAD Graph if you update an existing group's owners in a certain way, which makes me think there might be a race condition that's keeping this working in AAD Graph right now.

In order to try and keep track of the conversation around this issue, I'm going to close this issue in favor of #464. Please subscribe to that issue for further updates. Thanks!

**Comment by manicminer** [comment] 2021-07-02 16:03
Duplicate of #464

**Closed by manicminer** 2021-07-02 16:03 UTC
