### ISSUE TITLE
azuread_invitation - Allow ALL Properties To Be Set (Department, Job Title etc)

### ISSUE THREAD

**Issue by v1ferrarij** [hashicorp/terraform-provider-azuread#1113] opened 2023-06-06 11:29 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When using **azuread_invitation** to invite Guest Users, it would be good if we can set all the properties we can when performing the same task using Azure Portal/Azure CLI.

For example, I want to set 

First Name
Last Name
Job Title
Department 
Manager 

When using Terraform, however, I currently cannot do this with Terraform.

### New or Affected Resource(s)

azuread_invitation

### Potential Terraform Configuration

```hcl
resource "azuread_invitation" "example" {
  user_email_address = "john.smith@microsoft.com"
  user_display_name  = "John Smith"
  redirect_url = "https://portal.azure.com"

  first_name = "John"
  last_name = "Smith"
  job_title = "Azure Consultant"
  department = "Consultancy"
}
```

### References

* N/A

**Comment by OskarKlintrot** [comment] 2023-06-19 09:44
Is this a dup of #650?

**Comment by manicminer** [comment] 2023-07-25 21:49
Duplicate of #650

**Closed by manicminer** 2023-07-25 21:49 UTC

**Comment by manicminer** [comment] 2023-07-25 21:50
Thanks for raising this @v1ferrarij. We do intend to offer this functionality although the approach is likely to be that we roll some invitation functionality into the `azuread_user` resource rather than expanding the `azuread_invitation` resource.

This was already raised as a feature request in #650, so I've gone ahead and closed this as a duplicate, but please subscribe to #650 for updates on this. Thanks!
